name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    # Run always at YYYY-MM-03 03:03am
    - cron: '3 3 3 * *'
  workflow_dispatch:

jobs:
  build:
    name: Agda ${{ matrix.agda }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
        - os: ubuntu-latest
          agda: 2.6.4.1

    steps:

    # Checkout to $HOME empties $HOME so we have to do it before we put stuff there.
    - uses: actions/checkout@v4

    - name: Setup Agda
      uses: wenkokke/setup-agda@latest
      id:   setup
      with:
        agda-version: ${{ matrix.agda }}
        agda-stdlib-version: recommended

    - name: Restore cache
      uses: actions/cache/restore@v4
      id:   cache
      with:
        key:          ${{ runner.os }}-agda-${{ steps.setup.outputs.agda-version }}-commit-${{ github.sha }}
        restore-keys: ${{ runner.os }}-agda-${{ steps.setup.outputs.agda-version }}-
          # Don't have version of standard library. :-(
          # -std-lib-${{ matrix.std-lib }}
        path: |
          RBTree/_build
          ~/.agda/libraries.d
        # C:\Users\runneradmin\AppData\Roaming\agda\libraries.d\standard-library\v1.7.1

    - name: Run Agda
      run: make

    - name: Save cache
      uses: actions/cache/save@v4
      if: always()
      with:
        key:  ${{ steps.cache.outputs.cache-primary-key }}
        path: |
          RBTree/_build
          ~/.agda/libraries.d

    - uses: actions/upload-pages-artifact@v3
      with:
        path: RBTree/html

  # Deploy job, see https://github.com/actions/deploy-pages/tree/f81ad71d2e78487340fb3a94726f2a6050466efd#readme
  deploy:
    if: github.ref == 'refs/heads/master'
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages:    write   # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:

    - name: Deploy to GitHub Pages
      id:   deployment
      uses: actions/deploy-pages@v4
